[project]
name = "accounting-for-finances"
version = "0.1.0"
description = ""
authors = [
    {name = "Glavorn",email = "gleb.panov.07@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "uvicorn (>=0.51.0,<0.52.0)",
    "fastapi (>=0.140.9,<0.141.0)",
    "pydantic (>=2.13.4,<3.0.0)",
    "pydantic-settings (>=2.14.2,<3.0.0)",
    "alembic (>=1.18.5,<2.0.0)",
    "psycopg[binary] (>=3.3.4,<4.0.0)",
    "pyjwt (>=2.13.0,<3.0.0)",
    "argon2-cffi (>=25.1.0,<26.0.0)",


]

[tool.poetry]
packages = [{include = "accounting_for_finances", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
test = [
    "flake8 (>=7.3.0,<8.0.0)",
    "flake8-pyproject (>=1.2.4,<2.0.0)",
    "pep8-naming (>=0.15.1,<0.16.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-asyncio (>=1.4.0,<2.0.0)",
    "anyio (>=4.15.1,<5.0.0)",
    "pytest-tornasync (>=0.6.0.post2,<0.7.0)",
    "pytest-trio (>=0.8.0,<0.9.0)",
    "pytest-twisted (>=1.14.3,<2.0.0)",
    "twisted (>=26.4.0,<27.0.0)"
]
tets = [
    "pytest-asyncio (>=1.4.0,<2.0.0)"
]

[tool.flake8]
max-line-length = 130
ignore = [
    # W503: line break before binary operator
    "W503"
]
exclude = [
    ".git",
    "__pycache__",
    "conf",
    "venv",
    ".venv",
    ".vscode",
    ".idea",
]
per-file-ignores = [
#    "migrations/env.py:F401",
#    "migrations/versions/*:W291",
]