"""initial revision

Revision ID: 6f5604ee6e2d
Revises: 9690578b9b79
Create Date: 2026-07-30 20:42:52.035841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5604ee6e2d'
down_revision: Union[str, Sequence[str], None] = '9690578b9b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money_box',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('moneyboxname', sa.String(), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=False, foreign_key='users.id'),
    sa.Column('moneygoal', sa.Float(), nullable=False),
    sa.Column('moneybudget', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('money_box')
    # ### end Alembic commands ###
