"""Initial revision

Revision ID: 894b590ab920
Revises: fb9ec47abf08
Create Date: 2026-08-11 21:04:33.180840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894b590ab920'
down_revision: Union[str, Sequence[str], None] = 'fb9ec47abf08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_moneybox_user', 'money_box', ['userid', 'moneyboxname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_moneybox_user', table_name='money_box')
    # ### end Alembic commands ###
