"""initial revision

Revision ID: e6188bd93f7f
Revises: 6f5604ee6e2d
Create Date: 2026-07-30 20:51:20.180907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6188bd93f7f'
down_revision: Union[str, Sequence[str], None] = '6f5604ee6e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'money_box', 'user', ['userid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'money_box', type_='foreignkey')
    # ### end Alembic commands ###
