"""Initial revision

Revision ID: fb9ec47abf08
Revises: e6188bd93f7f
Create Date: 2026-08-11 20:55:10.494667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9ec47abf08'
down_revision: Union[str, Sequence[str], None] = 'e6188bd93f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_email', table_name='user')
    # ### end Alembic commands ###
